# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f66bd2e6add40501e26ff2dce3d16e95761c1b796e7a9ed2cd98d53de48670bce528db8a680622c41907e9c54d903b9eb0106336b307f87172dde0bb5dca36ea

test:
  secret_key_base: de5c1527b8f3cbb964c8822cf11ae9cb58fa5be0434e7565936339315ec9aafe8814b3aa22c65c8c1b23c8b715dbd07ba82f1b446bd0fb4e9880ab27ef81bea1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
